services:
  front:
    container_name: generic-forms-front
    build: ./client
    volumes:
      - ./client/src:/app/src
    ports:
      - 3000:3000
    environment:
      - WDS_SOCKET_PORT=3000
  api:
    container_name: generic-forms-api
    build: ./server
    volumes:
      - ./server/src:/app/src
    ports:
      - 4000:4000
    depends_on:
      dbtest:
        condition: service_healthy
  db:
    container_name: generic-forms-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: generic_forms
    ports:
      - 5431:5432
    volumes:
      - generic-forms-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d generic_forms -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
  dbtest:
    container_name: generic-forms-dbtest
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: generic_forms
    ports:
      - 5433:5432
    volumes:
      - generic-forms-test-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d generic_forms -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 10
  adminer:
    container_name: generic-forms-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      dbtest:
        condition: service_healthy
volumes:
  generic-forms-data:
  generic-forms-test-data:


