services:
  front:
    container_name: generic-forms-front
    image: genericforms/generic-forms-client
    command: sh -c "npm run build"
    ports:
      - 3000:3000
    environment:
      - WDS_SOCKET_PORT=3000
    env_file:
      - ./client/.env
    volumes:
    #/app/build folder will be mapped on a docker volume so not directly on the server
      - web-client-build:/app/build
  api:
    container_name: generic-forms-api
    image: genericforms/generic-forms-server
    command: sh -c "npm run build && npm run prod"
    ports:
      - 4000:4000
    env_file:
      - ./server/.env
    depends_on:
      dbtest:
        condition: service_healthy
      db:
        condition: service_healthy
  db:
    container_name: generic-forms-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: generic_forms
    ports:
      - 5431:5432
    volumes:
      - generic-forms-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d generic_forms -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
  dbtest:
    container_name: generic-forms-dbtest
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: generic_forms
    ports:
      - 5433:5432
    volumes:
      - generic-forms-test-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d generic_forms -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 10
  adminer:
    container_name: generic-forms-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
      dbtest:
        condition: service_healthy
  nginx:
    image: nginx:1.21.3
    depends_on:
      - front
      - api
    restart: always
    ports:
      - ${GATEWAY_PORT:-8000}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      #here we map the build folder of the front container on the nginx container
      - web-client-build:/web-client-build
      - ./logs:/var/log/nginx
volumes:
  generic-forms-data:
  generic-forms-test-data:
  web-client-build:


