export const themeConstants = {
    colors: {
      transparent: 'transparent' as const,
      white: 'white' as const,
      paperWhite: '#F9F9FF' as const,
      black: '#000000' as const,
      primaryMain: '#142C46' as const,
      primaryLight: '#E7F0FF' as const,
      primaryDark: '#142C46' as const,
      primaryContrast: '#FFFFFF' as const,
      secondary: '#16AF91' as const,
      secondaryHighlight: '#c8f0e9' as const,
      gray: '#F9F9FF' as const,
      mediumGray: '#627187' as const,
      semiLightGray: '#DFE8F5' as const,
      lightGray: '#9BA7B8' as const,
      error: '#B0154D' as const,
      success: '#16AF91' as const,
    },
    spacing: {
      quarterSm: 2 as const,
      quarter: 4 as const,
      demi: 8 as const,
      demiLG: 10 as const,
      demiXL: 12 as const,
      baseSm: 14 as const,
      base: 16 as const,
      baseLg: 20 as const,
      baseXl: 24 as const,
      screenPadding: 24 as const,
      doubleSm: 28 as const,
      double: 32 as const,
      triple: 48 as const,
      input: 40 as const,
      quadruple: 64 as const,
      quadrupleLG: 68 as const,
      quintuple: 80 as const,
      sixfold: 96 as const,
      octuple: 128 as const,
    },
    fontSize: {
      xxs: 10 as const,
      xs: 12 as const,
      sm: 14 as const,
      md: 16 as const,
      lg: 18 as const,
      lg2: 20 as const,
      xl: 22 as const,
      xl2: 24 as const,
      xl3: 26 as const,
      xl6: 45 as const,
    },
    fontWeight: {
      normal: '400' as const,
      bold: '700' as const,
    },
    radius: {
      full: 9999 as const,
      demi: 4 as const,
      base: 8 as const,
      baseLg: 10 as const,
      double: 16 as const,
      triple: 25 as const,
      quadruple: 32 as const,
    },
    opacity: {
      pressedSubtle: 0.75 as const,
      pressed: 0.5 as const,
      disabled: 0.5 as const,
    },
    fonts: {
      primary: 'Lato' as const,
    },
    components: {
      appBarHeight: 56 as const,
    }
  };