name: ESLint front
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache-dependency-path: client/package-lock.json
    - name: Install modules
      run: cd client && yarn
    - name: Run ESLint
      run: cd client && yarn eslint src/ --ext .js,.jsx,.ts,.tsx